### ISSUE TITLE
McPas-TCR dataset

### ISSUE THREAD

**Issue by adisabolic** [Lee-CBG/ATM-TCR#12]
Hello,

Could you maybe, if you still have it stored somewhere, send me the McPas-TCR unparsed dataset? The page to download it from is down, and I can't seem to find another source to download it from.

P.S. Actually if you can share all 3 unparsed datasets it would be amazing.

Thank you!

**Comment by cai-michael** [comment]
Hi @adisabolic, sorry for not getting back to you sooner. I'm no longer the primary maintainer on this project so I don't check it as often.

If you still need the datasets could you provide your email? I can send you an older copy of the datasets.

If posting your email publicly is less than preferable my old university email is `mrcai` at `asu` period `edu`. I don't check this as often either so reply to this comment when you send the email.

**Comment by adisa-eta** [comment]
Thank you @cai-michael ! I just sent you an email.

**Comment by adisabolic** [comment]
Thank you @cai-michael! I just sent you an email.

**Comment by cai-michael** [comment]
Emailed with the datasets :)

**Comment by yanpinlu** [comment]
> Thank you @cai-michael! I just sent you an email.

I have the same problem and cannot download the data of the IEDB database, can you send me the data from the above three databases? Thank you so much. My email address is 599509779@qq.com

**Comment by cai-michael** [comment]
Followed up with @yanpinlu in an email.

**Comment by yanpinlu** [comment]
> Followed up with @yanpinlu in an email.
I have received it. Thank you very much for your patient help
