### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JoshuaMeyers** [Lee-CBG/ATM-TCR#15]
Hey @cai-michael, very exciting work. What license have you released the code under? Would love to try it out at work. Cheers, J.

**Comment by cai-michael** [comment]
Hi @JoshuaMeyers! Sorry about that, I realized I never added a link to the publication which would specify the the [Creative Commons Attribution License (CC BY)](http://creativecommons.org/licenses/by/4.0/). I've merged a PR which includes the license information in the repo as well as a link to the Frontiers in Immunology paper.

Thanks for pointing this out :)
